ReservarCanchas_ProyectoProgramacionIV/Models/PersonalMantenimiento.cs
namespace ReservarCanchas_ProyectoProgramacionIV.Models
{
    public class PersonalMantenimiento : PersonaUdla
    {
        public PersonalMantenimiento()
        {
            TipoPersona = "Personal de Mantenimiento";
        }
    }
}

ReservarCanchas_ProyectoProgramacionIV/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservarCanchas_ProyectoProgramacionIV.Models;

namespace ReservarCanchas_ProyectoProgramacionIV.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly BaseDatos_ReservarCanchas_ProyectoProgramacionIV _context;

        public EstudiantesController(BaseDatos_ReservarCanchas_ProyectoProgramacionIV context)
        {
            _context = context;
        }

        // GET: Estudiantes
        public async Task<IActionResult> Index()
        {
            var baseDatos_ReservarCanchas_ProyectoProgramacionIV = _context.Estudiante.Include(e => e.Carrera);
            return View(await baseDatos_ReservarCanchas_ProyectoProgramacionIV.ToListAsync());
        }

        // GET: Estudiantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante
                .Include(e => e.Carrera)
                .FirstOrDefaultAsync(m => m.BannerId == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Estudiantes/Create
        public IActionResult Create()
        {
            ViewData["CarreraId"] = new SelectList(_context.Carrera, "Id", "Nombre");
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarreraId,BannerId,Nombre,Password,Correo,Telefono,Direccion,FechaNacimiento,TipoPersona")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarreraId"] = new SelectList(_context.Carrera, "Id", "Nombre", estudiante.CarreraId);
            return View(estudiante);
        }

        // GET: Estudiantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            ViewData["CarreraId"] = new SelectList(_context.Carrera, "Id", "Nombre", estudiante.CarreraId);
            return View(estudiante);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarreraId,BannerId,Nombre,Correo,Password,Telefono,Direccion,FechaNacimiento,TipoPersona")] Estudiante estudiante)
        {
            if (id != estudiante.BannerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.BannerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarreraId"] = new SelectList(_context.Carrera, "Id", "Nombre", estudiante.CarreraId);
            return View(estudiante);
        }

        // GET: Estudiantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante
                .Include(e => e.Carrera)
                .FirstOrDefaultAsync(m => m.BannerId == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiante = await _context.Estudiante.FindAsync(id);
            if (estudiante != null)
            {
                _context.Estudiante.Remove(estudiante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
            return _context.Estudiante.Any(e => e.BannerId == id);
        }
    }
}

ReservarCanchas_ProyectoProgramacionIV/Controllers/PersonalMantenimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservarCanchas_ProyectoProgramacionIV.Models;

namespace ReservarCanchas_ProyectoProgramacionIV.Controllers
{
    public class PersonalMantenimientosController : Controller
    {
        private readonly BaseDatos_ReservarCanchas_ProyectoProgramacionIV _context;

        public PersonalMantenimientosController(BaseDatos_ReservarCanchas_ProyectoProgramacionIV context)
        {
            _context = context;
        }

        // GET: PersonalMantenimientos
        public async Task<IActionResult> Index()
        {
            return View(await _context.PersonalMantenimiento.ToListAsync());
        }

        // GET: PersonalMantenimientos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personalMantenimiento = await _context.PersonalMantenimiento
                .FirstOrDefaultAsync(m => m.BannerId == id);
            if (personalMantenimiento == null)
            {
                return NotFound();
            }

            return View(personalMantenimiento);
        }

        // GET: PersonalMantenimientos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PersonalMantenimientos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BannerId,Nombre,Correo,Password,Telefono,Direccion,FechaNacimiento,TipoPersona")] PersonalMantenimiento personalMantenimiento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personalMantenimiento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personalMantenimiento);
        }

        // GET: PersonalMantenimientos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personalMantenimiento = await _context.PersonalMantenimiento.FindAsync(id);
            if (personalMantenimiento == null)
            {
                return NotFound();
            }
            return View(personalMantenimiento);
        }

        // POST: PersonalMantenimientos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BannerId,Nombre,Correo,Telefono,Direccion,FechaNacimiento,TipoPersona")] PersonalMantenimiento personalMantenimiento)
        {
            if (id != personalMantenimiento.BannerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personalMantenimiento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonalMantenimientoExists(personalMantenimiento.BannerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(personalMantenimiento);
        }

        // GET: PersonalMantenimientos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personalMantenimiento = await _context.PersonalMantenimiento
                .FirstOrDefaultAsync(m => m.BannerId == id);
            if (personalMantenimiento == null)
            {
                return NotFound();
            }

            return View(personalMantenimiento);
        }

        // POST: PersonalMantenimientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var personalMantenimiento = await _context.PersonalMantenimiento.FindAsync(id);
            if (personalMantenimiento != null)
            {
                _context.PersonalMantenimiento.Remove(personalMantenimiento);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonalMantenimientoExists(int id)
        {
            return _context.PersonalMantenimiento.Any(e => e.BannerId == id);
        }
    }
}

ReservarCanchas_ProyectoProgramacionIV/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservarCanchas_ProyectoProgramacionIV.Models;

namespace ReservarCanchas_ProyectoProgramacionIV.Controllers
{
    public class ReservasController : Controller
    {
        private readonly BaseDatos_ReservarCanchas_ProyectoProgramacionIV _context;

        public ReservasController(BaseDatos_ReservarCanchas_ProyectoProgramacionIV context)
        {
            _context = context;
        }

        // GET: Reservas
        public async Task<IActionResult> Index()
        {
            var baseDatos_ReservarCanchas_ProyectoProgramacionIV = _context.Reserva.Include(r => r.Cancha).Include(r => r.PersonaUdla);
            return View(await baseDatos_ReservarCanchas_ProyectoProgramacionIV.ToListAsync());
        }

        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva
                .Include(r => r.Cancha)
                .Include(r => r.PersonaUdla)
                .FirstOrDefaultAsync(m => m.ReservaId == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        public IActionResult Create()
        {
            ViewData["CanchaId"] = new SelectList(_context.Cancha, "CanchaId", "CanchaId");
            ViewData["PersonaUdlaId"] = new SelectList(_context.Set<PersonaUdla>(), "BannerId", "Nombre");
            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReservaId,FechaInicio,FechaFin,CanchaId,PersonaUdlaId")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CanchaId"] = new SelectList(_context.Cancha, "CanchaId", "CanchaId", reserva.CanchaId);
            ViewData["PersonaUdlaId"] = new SelectList(_context.Set<PersonaUdla>(), "BannerId", "Nombre", reserva.PersonaUdlaId);
            return View(reserva);
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return NotFound();
            }
            ViewData["CanchaId"] = new SelectList(_context.Cancha, "CanchaId", "CanchaId", reserva.CanchaId);
            ViewData["PersonaUdlaId"] = new SelectList(_context.Set<PersonaUdla>(), "BannerId", "Nombre", reserva.PersonaUdlaId);
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReservaId,FechaInicio,FechaFin,CanchaId,PersonaUdlaId")] Reserva reserva)
        {
            if (id != reserva.ReservaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserva);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservaExists(reserva.ReservaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CanchaId"] = new SelectList(_context.Cancha, "CanchaId", "CanchaId", reserva.CanchaId);
            ViewData["PersonaUdlaId"] = new SelectList(_context.Set<PersonaUdla>(), "BannerId", "Nombre", reserva.PersonaUdlaId);
            return View(reserva);
        }

        // GET: Reservas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva
                .Include(r => r.Cancha)
                .Include(r => r.PersonaUdla)
                .FirstOrDefaultAsync(m => m.ReservaId == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reserva = await _context.Reserva.FindAsync(id);
            if (reserva != null)
            {
                _context.Reserva.Remove(reserva);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservaExists(int id)
        {
            return _context.Reserva.Any(e => e.ReservaId == id);
        }
    }
}

ReservarCanchas_ProyectoProgramacionIV/Views/PersonalMantenimientos/Create.cshtml
@model ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PersonalMantenimiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" /> |
                <a class="btn btn-primary" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReservarCanchas_ProyectoProgramacionIV/Views/PersonalMantenimientos/Delete.cshtml
@model ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Seguro que quieres eliminar este usuario?</h3>
<div>
    <h4>PersonalMantenimiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoPersona)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BannerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </form>
</div>

ReservarCanchas_ProyectoProgramacionIV/Views/PersonalMantenimientos/Details.cshtml
@model ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PersonalMantenimiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoPersona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoPersona)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.BannerId">Edit</a> |
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

ReservarCanchas_ProyectoProgramacionIV/Views/PersonalMantenimientos/Edit.cshtml
@model ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PersonalMantenimiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BannerId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoPersona" class="control-label"></label>
                <input asp-for="TipoPersona" class="form-control" />
                <span asp-validation-for="TipoPersona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" /> |
                <a class="btn btn-primary" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ReservarCanchas_ProyectoProgramacionIV/Views/PersonalMantenimientos/Index.cshtml
@model IEnumerable<ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento>

@{
	ViewData["Title"] = "Index";
}

<p>
	<a asp-controller="Administradores" asp-action="Index" class="btn btn-secondary">
		<i></i> Administradores
	</a>
	<a asp-controller="Estudiantes" asp-action="Index" class="btn btn-secondary">
		<i></i> Estudiantes
	</a>
	<a asp-controller="Reservas" asp-action="Index" class="btn btn-secondary">
		<i></i> Reservas
	</a>
</p>

<h1>Personal de Mantenimiento</h1>

<p>
	<a asp-action="Create" class="btn btn-primary">
		<i class="bi bi-plus-circle"></i> Crear Nuevo Administrador
	</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nombre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Correo)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Telefono)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Direccion)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.FechaNacimiento)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.TipoPersona)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Nombre)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Correo)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Telefono)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Direccion)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.FechaNacimiento)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.TipoPersona)
				</td>
				<td>
					<a asp-action="Edit" class="btn btn-outline-warning" asp-route-id="@item.BannerId">
						<i class="bi bi-pencil-square"></i> Edit
					</a> |
					<a asp-action="Details" class="btn btn-outline-info" asp-route-id="@item.BannerId">
						<i class="bi bi-eye"></i> Details
					</a> |
					<a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.BannerId">
						<i class="bi bi-trash"></i> Delete
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>